name: Update README.md

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

env:
  APP_NAME: 'test-wiki'

jobs:
  Update_README:
    name: Update README.md
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR merged with Main
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        with:
          ref: refs/pull/${{ github.event.number }}/merge
      
      - name: Checkout Main
        uses: actions/checkout@v3

      - name: Upload Coverage Badge
        uses: actions/upload-artifact@v3
        with:
          name: coverage-badge
          path: ${{ env.APP_NAME }}-coverage-badge.svg

      # - name: Build-A-Badge
      #   uses: peterrhodesdev/build-a-badge@v1.3.1
      #   with:
      #     token: ${{ secrets.GH_TOKEN }}
      #     filename: my-badge
      #     label: coverage
      #     message: 88.18%

  Upload_SVG_Badge:
    name: Upload SVG badge
    runs-on: ubuntu-latest
    needs: [ Update_README ]

    steps:

      - name: Checkout repo wiki
        uses: actions/checkout@v3
        with: 
          repository: cctan777/${{ env.APP_NAME }}.wiki

      - name: Check contents of folder
        run: ls -al

      - name: Check Badge existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: ${{ env.APP_NAME }}-coverage-badge.svg
#          files: "${{ env.APP_NAME }}-coverage-badge.svg"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          rm -f ${{ env.APP_NAME }}-coverage-badge.svg
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add changes"
          git push
#####################################################################################################
#      - name: Delete Existing Badge (if exists)
#        env:
#          BADGE_EXISTS: ${{ if }}
#        run: |
#          rm -f NoiseOptimiser-coverage-badge.svg
##          [ -e NoiseOptimiser-coverage-badge.svg ] && rm NoiseOptimiser-coverage-badge.svg

      - name: Check to see if the file has been deleted
        run: ls -al

#      - name: Commit Change
#        run: |
#          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#          git config --local user.name "github-actions[bot]"
#          git add .
#          git commit -m "Add changes"

#      - name: Push 
#        if: always()
#        run: |
#          git push

      - name: Download Coverage Badge From Artifacts
        uses: actions/download-artifact@v3
        with:
          name: coverage-badge
          path: ./

      # - name: change timestamp of coverage badge
      #   run: |
      #     touch -d "2 hours ago" NoiseOptimiser-coverage-badge.svg

      - name: Check contents of repo wiki
        run: ls -al

      - name: Commit Change
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add changes"
          git push

      # - name: Push 
      #   if: always()
      #   run: |
      #     git push
