name: Update README.md

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

env:
  APP_NAME: 'test-wiki'

jobs:
  Update_README:
    name: Update README.md
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR merged with Main
        uses: actions/checkout@v3
        if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        with:
          ref: refs/pull/${{ github.event.number }}/merge
      
      - name: Checkout Main
        uses: actions/checkout@v3

      - name: Extract Badge From Code Coverage Results
        run: |
          badge=$(head -n 1 ${{ env.APP_NAME }}-coverage-results.md)
          echo $badge
          badge=`echo $badge | cut -c 18-`
          badge=`echo $badge | sed 's/.$//'`
          echo $badge

      - name: Get Current Branch Name
        run: |
          echo Branch name is ${GITHUB_REF##*/}
          echo Branch name is ${{ github.ref_name }}
          echo Branch name is ${{ github.head_ref }}

      # - name: Update README.md with Code Coverage Badge
      #   run: sed -i -e "s|<coverage-badge>.*</coverage-badge>|<coverage-badge>[![]($badge)]()<r$RANDOM$RANDOM></coverage-badge>|g" README.md

      - name: Upload Coverage Badge
        uses: actions/upload-artifact@v3
        with:
          name: results-and-badge
          path: |
            ${{ env.APP_NAME }}-coverage-results.md
            ${{ env.APP_NAME }}-coverage-badge.svg

      # - name: Build-A-Badge
      #   uses: peterrhodesdev/build-a-badge@v1.3.1
      #   with:
      #     token: ${{ secrets.GH_TOKEN }}
      #     filename: my-badge
      #     label: coverage
      #     message: 88.18%

  Upload_SVG_Badge:
    name: Upload SVG badge
    runs-on: ubuntu-latest
    needs: [ Update_README ]

    steps:

      - name: Checkout repo wiki
        uses: actions/checkout@v3
        with: 
          repository: cctan777/${{ env.APP_NAME }}.wiki

      - name: Check contents of folder
        run: ls -al

      # - name: Check Badge existence
      #   id: check_files
      #   uses: andstor/file-existence-action@v2
      #   with:
      #     files: ${{ env.APP_NAME }}-coverage-badge.svg, ${{ env.APP_NAME }}-coverage-results.md

      # - name: File exists
      #   if: steps.check_files.outputs.files_exists == 'true'
      #   run: |
      #     rm -f ${{ env.APP_NAME }}-coverage-badge.svg ${{ env.APP_NAME }}-coverage-results.md
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     git add .
      #     git commit -m "Add changes"
      #     git push

      # - name: Check to see if the file has been deleted
      #   if: steps.check_files.outputs.files_exists == 'true'
      #   run: ls -al

      - name: Download Coverage Badge From Artifacts
        uses: actions/download-artifact@v3
        with:
          name: results-and-badge
          path: ./

      - name: Check contents of repo wiki
        run: ls -al

      - name: Commit Change
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add changes"
          git push
